// Generated by tools/gen_thermistor_table.py -- do not edit by hand.
//
// Thermistor: B = 4275, R0 = 100000 ohm at 298.15 K
// Breakpoint every 8 ADC counts, 129 entries, tenths of a degree Celsius.

#pragma once

#include <stdint.h>

namespace thermostat {
namespace table {

constexpr uint16_t kStep = 8;
constexpr uint16_t kEntryCount = 129;

// ADC counts outside this window mean a disconnected or shorted thermistor.
constexpr uint16_t kMinValidCount = 24;
constexpr uint16_t kMaxValidCount = 992;

// Reads one breakpoint. On AVR the data lives in flash, so this is not a plain
// array subscript -- see Progmem.h.
int16_t entry(uint16_t index);

}  // namespace table
}  // namespace thermostat
