// Generated by tools/gen_thermistor_table.py -- do not edit by hand.
//
// Thermistor: B = 4275, R0 = 100000 ohm at 298.15 K
// Breakpoint every 8 ADC counts, 129 entries, tenths of a degree Celsius.

#include "thermostat/ThermistorTable.h"

#include "thermostat/Progmem.h"

namespace thermostat {
namespace table {
namespace {

const int16_t kDeciCelsius[kEntryCount] THERMOSTAT_PROGMEM = {
      -721,   -503,   -418,   -365,   -326,   -294,   -267,   -244,
      -223,   -205,   -188,   -172,   -157,   -143,   -130,   -118,
      -106,    -95,    -84,    -74,    -64,    -54,    -44,    -35,
       -26,    -18,     -9,     -1,      7,     15,     23,     31,
        38,     45,     53,     60,     67,     74,     81,     88,
        95,    102,    108,    115,    122,    128,    135,    141,
       148,    154,    161,    167,    173,    180,    186,    193,
       199,    205,    212,    218,    225,    231,    237,    244,
       250,    257,    263,    270,    277,    283,    290,    297,
       304,    311,    317,    325,    332,    339,    346,    353,
       361,    368,    376,    384,    391,    399,    408,    416,
       424,    433,    442,    450,    460,    469,    478,    488,
       498,    509,    519,    530,    542,    553,    565,    578,
       591,    605,    619,    634,    649,    665,    683,    701,
       720,    741,    763,    787,    813,    842,    874,    909,
       949,    995,   1050,   1116,   1200,   1314,   1488,   1835,
      3039,
};

}  // namespace

int16_t entry(uint16_t index) {
    if (index >= kEntryCount) {
        index = kEntryCount - 1;
    }
    return readTableWord(&kDeciCelsius[index]);
}

}  // namespace table
}  // namespace thermostat
