"""Generate the ADC-count -> temperature lookup table for the Grove thermistor.

The conversion needs a natural logarithm, which the ATmega328P has no business
doing at runtime: there is no FPU, and linking libm costs flash for an operation
we can precompute. So the curve is sampled here, checked into the repository, and
read back on the target with linear interpolation between breakpoints.

Run from the project root:
    python tools/gen_thermistor_table.py

Grove - Temperature Sensor wiring (Seeed reference design):
    the thermistor sits in a divider with a fixed R0 resistor, so
        R_thermistor = R0 * (1023 / adc - 1)
    and the B-parameter equation gives
        1 / T = 1 / T0 + (1 / B) * ln(R / R0)

Check your module revision before trusting the defaults. v1.1 and v1.2 use a
100k thermistor with B = 4275; older v1.0 boards use B = 3975 with R0 = 10k.
"""

import math
import os

# --- sensor parameters -------------------------------------------------------
B_VALUE = 4275.0          # B constant of the thermistor, from the datasheet
R0_OHMS = 100000.0        # nominal resistance at T0
T0_KELVIN = 298.15        # 25 degrees C

# --- table shape -------------------------------------------------------------
ADC_MAX = 1023            # 10-bit ADC
STEP = 8                  # one breakpoint every STEP counts
ENTRY_COUNT = ADC_MAX // STEP + 2   # +1 for index 0, +1 so interpolation can read index+1

# --- the range we are willing to believe ------------------------------------
# The sensor is specified for -40..125 C. Outside that the divider is telling us
# about a broken thermistor, not about the room, so the controller treats it as
# a fault rather than a reading.
VALID_MIN_DECI = -400
VALID_MAX_DECI = 1250

HEADER_PATH = os.path.join("lib", "thermostat", "include", "thermostat", "ThermistorTable.h")
SOURCE_PATH = os.path.join("lib", "thermostat", "src", "ThermistorTable.cpp")


def deci_celsius(adc):
    """Temperature in tenths of a degree Celsius for a raw ADC count.

    Both rails are electrically meaningless: at 0 the divider says the
    thermistor is infinite, at 1023 it says zero ohms. Clamp into the interior
    so the table stays finite; the validity window below is what actually
    rejects them.
    """
    clamped = min(max(adc, 1), ADC_MAX - 1)
    resistance = R0_OHMS * (ADC_MAX / clamped - 1.0)
    inv_t = 1.0 / T0_KELVIN + math.log(resistance / R0_OHMS) / B_VALUE
    celsius = 1.0 / inv_t - 273.15
    return int(round(celsius * 10.0))


def build_table():
    return [deci_celsius(i * STEP) for i in range(ENTRY_COUNT)]


def valid_window(table):
    """Smallest and largest ADC count whose interpolated reading we trust.

    Reported on breakpoint boundaries, which is conservative: a count just
    inside a rejected breakpoint is rejected too.
    """
    lo, hi = None, None
    for index, value in enumerate(table):
        if VALID_MIN_DECI <= value <= VALID_MAX_DECI:
            count = index * STEP
            if lo is None:
                lo = count
            hi = count
    if lo is None:
        raise SystemExit("no ADC count produces a temperature inside the valid window")
    return lo, hi


BANNER = """// Generated by tools/gen_thermistor_table.py -- do not edit by hand.
//
// Thermistor: B = {b:.0f}, R0 = {r0:.0f} ohm at {t0:.2f} K
// Breakpoint every {step} ADC counts, {count} entries, tenths of a degree Celsius.
"""


def write_header(table, valid_lo, valid_hi):
    banner = BANNER.format(b=B_VALUE, r0=R0_OHMS, t0=T0_KELVIN, step=STEP, count=len(table))
    body = """#pragma once

#include <stdint.h>

namespace thermostat {{
namespace table {{

constexpr uint16_t kStep = {step};
constexpr uint16_t kEntryCount = {count};

// ADC counts outside this window mean a disconnected or shorted thermistor.
constexpr uint16_t kMinValidCount = {valid_lo};
constexpr uint16_t kMaxValidCount = {valid_hi};

// Reads one breakpoint. On AVR the data lives in flash, so this is not a plain
// array subscript -- see Progmem.h.
int16_t entry(uint16_t index);

}}  // namespace table
}}  // namespace thermostat
""".format(step=STEP, count=len(table), valid_lo=valid_lo, valid_hi=valid_hi)
    os.makedirs(os.path.dirname(HEADER_PATH), exist_ok=True)
    with open(HEADER_PATH, "w", newline="\n") as handle:
        handle.write(banner + "\n" + body)


def write_source(table):
    lines = []
    for chunk_start in range(0, len(table), 8):
        chunk = table[chunk_start:chunk_start + 8]
        lines.append("    " + ", ".join("{:6d}".format(v) for v in chunk) + ",")
    banner = BANNER.format(b=B_VALUE, r0=R0_OHMS, t0=T0_KELVIN, step=STEP, count=len(table))
    body = """#include "thermostat/ThermistorTable.h"

#include "thermostat/Progmem.h"

namespace thermostat {{
namespace table {{
namespace {{

const int16_t kDeciCelsius[kEntryCount] THERMOSTAT_PROGMEM = {{
{rows}
}};

}}  // namespace

int16_t entry(uint16_t index) {{
    if (index >= kEntryCount) {{
        index = kEntryCount - 1;
    }}
    return readTableWord(&kDeciCelsius[index]);
}}

}}  // namespace table
}}  // namespace thermostat
""".format(rows="\n".join(lines))
    os.makedirs(os.path.dirname(SOURCE_PATH), exist_ok=True)
    with open(SOURCE_PATH, "w", newline="\n") as handle:
        handle.write(banner + "\n" + body)


def main():
    table = build_table()
    valid_lo, valid_hi = valid_window(table)
    write_header(table, valid_lo, valid_hi)
    write_source(table)

    print("wrote {} and {}".format(HEADER_PATH, SOURCE_PATH))
    print("entries: {}, step: {}".format(len(table), STEP))
    print("valid ADC window: {}..{}".format(valid_lo, valid_hi))
    print("\nreference points for the host tests:")
    for adc in (valid_lo, 256, 384, 512, 640, 768, valid_hi):
        print("    adc {:4d} -> {:6.1f} C".format(adc, deci_celsius(adc) / 10.0))


if __name__ == "__main__":
    main()
